services:
  retail_postgres:
    image: postgres:16-alpine
    container_name: retail_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: retail_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@retail.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      retail_postgres:
        condition: service_healthy

  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: retail_airflow
    restart: unless-stopped
    depends_on:
      retail_postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@retail_postgres:5432/retail_airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=46d229e0ee43f0acba0f476bc4006ff8
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - PYTHONPATH=/opt/airflow
      - POSTGRES_HOST=retail_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OLTP_DB_NAME=retail_oltp
      - OLAP_DB_NAME=retail_olap
    volumes:
      - ./data_engineering/airflow/dags:/opt/airflow/dags
      - ./data_engineering:/opt/airflow/data_engineering
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: standalone

volumes:
  postgres_data:
